# Generated by Django 3.1.7 on 2021-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('purchase_price', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('selling_price', models.IntegerField(null=True)),
                ('selling_date', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tags', models.TextField(default='[]')),
            ],
        ),
    ]
