# Generated by Django 3.1.7 on 2021-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leBeau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='selling_date',
            field=models.DateField(default='unsold', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='selling_price',
            field=models.IntegerField(default='', null=True),
        ),
    ]
