# Generated by Django 3.1.7 on 2021-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leBeau', '0005_auto_20210312_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='lebeau/thumbnails'),
        ),
    ]
