# Generated by Django 3.1.7 on 2021-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leBeau', '0007_transaction_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='selling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
