# Generated by Django 3.1.7 on 2021-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_key_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='icons',
            new_name='deployment_icons',
        ),
        migrations.AddField(
            model_name='project',
            name='language_icons',
            field=models.TextField(default='[]'),
        ),
    ]
