# Generated by Django 3.1.7 on 2021-03-30 15:10

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=25)),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[64, 90], upload_to='')),
                ('next_5', models.TextField(default='[]')),
            ],
        ),
    ]
