# Generated by Django 3.1.7 on 2021-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0003_auto_20210330_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.IntegerField(),
        ),
    ]
