# Generated by Django 3.1.7 on 2021-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0004_auto_20210403_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_5',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.IntegerField(),
        ),
    ]
