# Generated by Django 3.1.7 on 2021-04-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0006_team_standings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='league',
            new_name='league_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='team_id',
        ),
    ]
