# Generated by Django 3.2.3 on 2021-05-19 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0007_auto_20210404_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 17, 12, 6, 240450)),
        ),
    ]
