# Generated by Django 3.2.3 on 2021-05-19 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0008_team_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 19, 14, 8, 228665)),
        ),
    ]
