# Generated by Django 3.2.3 on 2021-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0009_alter_team_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
